### ISSUE TITLE
Pin 25 (for on-board LED) not valid

### ISSUE THREAD

**Issue by DeeJay** [MrYsLab/telemetrix-rpi-pico#11]
Pin 25 (for on-board LED) not valid

**Blink** and **Fade** examples failing.

`>>> board.set_pin_mode_digital_output(25)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/telemetrix_rpi_pico/telemetrix_rpi_pico.py", line 788, in set_pin_mode_digital_output
    self._set_pin_mode(pin_number, PrivateConstants.AT_OUTPUT)
  File "/usr/local/lib/python3.9/dist-packages/telemetrix_rpi_pico/telemetrix_rpi_pico.py", line 1335, in _set_pin_mode
    raise RuntimeError('Gpio Pin Number is invalid')
RuntimeError: Gpio Pin Number is invalid
>>>
`

**Comment by MrYsLab** [comment]
This is where rushing gets one ;-)  I totally forgot that GPIO 25 is the board LED. It will be fixed with release 1.3.

**Comment by MrYsLab** [comment]
Fixed with release 1.3
